pull_request_rules:
  - name: ✔️ Automatic merge on pull request approval
    conditions:
      - approved-reviews-by>=1
      - check-success=laravel-tests
      - check-success=GitGuardian Security Checks
    actions:
      merge:
        method: merge
      comment:
        message: ✔️ Automatic merge on pull request approval
  - name: 📦 Automatic merge on @dependabot pull request
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - label=dependencies
      - check-success=laravel-tests
      - check-success=GitGuardian Security Checks
    actions:
      merge:
        method: merge
        strict: smart
      comment:
        message: 📦 Automatic merge on @dependabot pull request
